### ISSUE TITLE
Processing Pattern Tasks may not be (re)started when Grid Members join/leave a Cluster

### ISSUE THREAD

**Issue by jfialli** [coherence-community/coherence-incubator#173]
When a cache server joins/leaves a cluster, in flight executing Processing Pattern tasks may migrate to anther cache server cluster member.  the following log message indicates a failure for that process to be restarted when migrated.

Oracle Coherence GE 3.7.1.19 <Warning> (thread=DistributedCache:DistributedServiceForProcessingPatternSubmissionResults, member=1): Could not set DefaultSubmissionResult [owner=TPSK:{Identifier{XXXX},0,0x0A8786B700000174236A89234EF63425}, submissionState=ASSIGNED, sessionIdentifier=Identifier{0x000001745D1D7CF80A8786B68EBA42F1CB5B9866330F204DC3D461E6432CD0BF}, submissionKey=0x000001745D1D7DE80A8786B6B92A2D7B4E4D0D9E4B4FF124CEE32A63432CD0C0, submissionResultID=Identifier{YYYYYYYYYY}, latency=0, executionTime=0, isResuming=false, startTime=0, submissionTime=1599290047977] to ASSIGNED because it was not in SUBMITTED, SUSPENDED or RETRY state Class:com.oracle.coherence.patterns.processing.internal.DefaultSubmissionResult Method:assign> 

This log message was also observed in log files.

java.lang.NullPointerException: Tried to execute method:offerTask but Entry is null, key:TPSK:{Identifier{XXXXXXXXXXXX},0,0x0A8786B60000017489D2E2AE2EE0FB07}

A partial back merge of relevant changes for develop-11 branch from develop-12 branch fix for #163 is fix for this issue.

Recreated above warning log message running coherence-processingpattern-examples TaskExecutionExample against 3 cache servers.
While running client, stopped and restarted one of the cache servers.  Before fix, recreated Warning above.  After fix in DefaultSubmissionResult, the failure is no longer occurring.

**Comment by lsho** [comment]
Change looks good
